---
- name: Make sure the EPEL repository is available
  template: >
    src=epel.repo 
    dest=/etc/yum.repos.d/epel.repo 
    owner=root group=root mode=644

- name: Make the Sensu repository is available
  template: >
    src=sensu.repo
    dest=/etc/yum.repos.d/sensu.repo
    owner=root group=root mode=644

- name: Make the MongoDB repository available
  template: >
     src=mongo.repo 
     dest=/etc/yum.repos.d/mongo.repo
     owner=root group=root mode=644

- name: Install the Dependencies that are needed 
  yum: pkg={{ item }} state=installed
  with_items:
    - wget
    - python-pip
    - erlang
    - redis
    - java-1.7.0-openjdk
    - openssl
    - gcc
    - zlib-devel
    - python 
    - python-ldap
    - python-memcached
    - python-twisted
    - python-sqlite2
    - pycairo
    - Django14
    - django-tagging
    - bitmap
    - bitmap-fonts
    - python-devel
    - glibc-devel
    - openssl-devel
    - python-zope-interface
    - httpd
    - memcached 
    - mod_wsgi
    - sysstat
    - bc
    - nc
    - libyaml
    - ruby

- name: Install dpendencies with python-pip
  pip: name={{ item }} state=present
  with_items:
    - supervisor
    - txAMQP
    - whisper
    - carbon

- name: Install the RabbitMQ server
  yum: name={{ item }} state=installed
  with_items:
    - http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    - http://www.rabbitmq.com/releases/rabbitmq-server/v3.1.5/rabbitmq-server-3.1.5-1.noarch.rpm

- name: Install Sensu core by rpm file
  yum: name=sensu state=installed

- name: Install sensu ruby sensu-plugin
  gem: name=sensu-plugin state=present
