---
- name: Ensure the sensu vhost exists on rabbitMQ
  rabbitmq_vhost: name=/sensu state=present

- name: Add rabbitmq sensu to server and assign full access control
  rabbitmq_user: user=sensu password={{ my_secret }} vhost=/sensu configure_priv=.* read_priv=.* write_priv=.* state=present

- name: Copy the rabbitmq config file over
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config owner=rabbitmq group=rabbitmq mode=0644 backup=yes

- name: Copy the sensu config files over
  template: src=config.json.j2 dest=/etc/sensu/config.json owner=root